FROM openjdk:8-jre-slim

##jmeter版本
ARG JMETER_VERSION=5.5

#安装必要软件
RUN apt-get clean && \
    apt-get update && \
    apt-get -qy install \
                wget \
                telnet \
                net-tools \
                vim

#防止vim安装失败
RUN apt-get update --fix-missing && apt-get install -y vim --fix-missing

#安装jmeter
RUN mkdir /jmeter \
	&& cd /jmeter/ \
#	国内镜像高速下载jmeter
	&& wget https://mirrors.aliyun.com/apache/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
#	官方下载jmeter
#	&& wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
	&& tar -xzf apache-jmeter-$JMETER_VERSION.tgz  \
	&& cp -r ./apache-jmeter-$JMETER_VERSION/* . \
	&& rm -rf apache-jmeter-$JMETER_VERSION.tgz ./apache-jmeter-$JMETER_VERSION

#JMETER_HOME环境变量
#ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION/
ENV JMETER_HOME /jmeter/
ENV PATH $JMETER_HOME/bin:$PATH

WORKDIR $JMETER_HOME

#脚本复制到当前路径
COPY ./user.properties bin/user.properties
COPY ./install_plugin_manager.sh bin
COPY ./entrypoint.sh bin

RUN chmod +x bin/install_plugin_manager.sh
RUN chmod +x bin/entrypoint.sh
RUN bin/install_plugin_manager.sh

EXPOSE 60000 1099 50000
ENTRYPOINT ["bin/entrypoint.sh"]







